django/order_project/order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('', views.HomeListView.as_view(), name='home'),
    path('report/', views.ReportListView.as_view(), name='report'),
    path('menu/<int:pk>/', views.menu, name='menu'),
    path('del_b/<int:pk>/', views.BreakfastOrderDeleteView.as_view(), name='delete_b'),
    path('del_l/<int:pk>/', views.LunchOrderDeleteView.as_view(), name='delete_l'),
    path('del_d/<int:pk>/', views.DinnerOrderDeleteView.as_view(), name='delete_d'),


    # path('create/', views.RoomCreate.as_view(), name='create'),
    # path('delete/<int:pk>/', views.RoomDeleteView.as_view(), name='delete'),
    # path('create_db/', views.create_db, name='create_db'),
]

django/order_project/order_project/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('order/', include('order.urls')),
]

django/order_project/order/models.py
from django.db import models
from django_currentuser.db.models import CurrentUserField


class Floor(models.Model):
    floor_num     = models.PositiveSmallIntegerField(unique=True)

    def __str__(self):
        return str(self.floor_num)


ROOM_STATUS  = (
    ('OCC', 'Occupied'),
    ('CO', 'Check Out'),
    ('V', 'Vacant'),

)


class Room(models.Model):
    floor         = models.ForeignKey(Floor, on_delete=models.CASCADE)
    room_num      = models.PositiveSmallIntegerField(unique=True)
    adult         = models.PositiveSmallIntegerField(default=1)
    kid           = models.PositiveSmallIntegerField(default=0)
    status        = models.CharField(max_length=20, choices=ROOM_STATUS, default='Vacant')

    def __str__(self):
        return str(self.room_num)


    def save_model(self, request, obj, form, change):
        if not change:
            account = Account.objects.get(email=request.user)
            obj.floor = account.floors.all().first()
        obj.save()


class Tag(models.Model):
    tag_name = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.tag_name



DAYS = (
    ('0', 'Monday'),
    ('1', 'Tuesday'),
    ('2', 'Wednesday'),
    ('3', 'Thursday'),
    ('4', 'Friday'),
    ('5', 'Saturday'),
    ('6', 'Sunday'),
)



class Starter(models.Model):
    starter_name  = models.CharField(max_length=100, null=True, blank=True)
    date_created  = models.DateTimeField(auto_now_add=True, null=True)
    tags          = models.ManyToManyField(Tag)
    day           = models.CharField(max_length=3, choices=DAYS, null=True)

    def __str__(self):
        return self.starter_name


class Main(models.Model):
    main_name     = models.CharField(max_length=100, null=True, blank=True)
    date_created  = models.DateTimeField(auto_now_add=True, null=True)
    tags          = models.ManyToManyField(Tag)
    day           = models.CharField(max_length=3, choices=DAYS, null=True)

    def __str__(self):
        return self.main_name


class Dessert(models.Model):
    dessert_name  = models.CharField(max_length=100, null=True, blank=True)
    date_created  = models.DateTimeField(auto_now_add=True, null=True)
    tags          = models.ManyToManyField(Tag)
    day           = models.CharField(max_length=3, choices=DAYS, null=True)
    
    def __str__(self):
        return self.dessert_name


ORDER_STATUS  = (
    ('pending', 'Pending'),
    ('delivered', 'Delivered'),
    ('cancelled', 'Cancelled'),

)


class BreakfastOrder(models.Model):
    user          = CurrentUserField()
    room          = models.ForeignKey(Room, null=True, on_delete=models.SET_NULL)
    is_needed     = models.BooleanField(default=False, null=True)
    ordered_date  = models.DateTimeField(auto_now_add=True, null=True)
    updated_date  = models.DateTimeField(auto_now=True, null=True)
    delivery_time = models.DateTimeField(blank=True, null=True)
    comment       = models.CharField(max_length=200, blank=True, null=True)
    status        = models.CharField(max_length=20, choices=ORDER_STATUS, default='Pending')

    def __str__(self):
        return str(self.room)


class LunchOrder(models.Model):
    user          = CurrentUserField()
    room          = models.ForeignKey(Room, null=True, on_delete=models.SET_NULL)
    starter       = models.ForeignKey(Starter, blank=True, null=True, on_delete=models.SET_NULL)
    main          = models.ForeignKey(Main, blank=True, null=True, on_delete=models.SET_NULL)
    dessert       = models.ForeignKey(Dessert, blank=True, null=True, on_delete=models.SET_NULL)
    ordered_date  = models.DateTimeField(auto_now_add=True, null=True)
    updated_date  = models.DateTimeField(auto_now=True, null=True)
    delivery_time = models.DateTimeField(blank=True, null=True)
    comment       = models.CharField(max_length=200, blank=True, null=True)
    status        = models.CharField(max_length=20, choices=ORDER_STATUS, default='pending')

    def __str__(self):
        return str(self.room)


class DinnerOrder(models.Model):
    user          = CurrentUserField()
    room          = models.ForeignKey(Room, null=True, on_delete=models.SET_NULL)
    starter       = models.ForeignKey(Starter, blank=True, null=True, on_delete=models.SET_NULL)
    main          = models.ForeignKey(Main, blank=True, null=True, on_delete=models.SET_NULL)
    dessert       = models.ForeignKey(Dessert, blank=True, null=True, on_delete=models.SET_NULL)
    ordered_date  = models.DateTimeField(auto_now_add=True, null=True)
    updated_date  = models.DateTimeField(auto_now=True, null=True)
    delivery_time = models.DateTimeField(blank=True, null=True)
    comment       = models.CharField(max_length=200, blank=True, null=True)
    status        = models.CharField(max_length=20, choices=ORDER_STATUS, default='pending')

    def __str__(self):
        return str(self.room)

django/order_project/order/forms.py
import datetime
from django import forms
from .models import BreakfastOrder, LunchOrder, DinnerOrder, Starter, Main, Dessert


class BreakfastOrderForm(forms.ModelForm):
    is_needed = forms.BooleanField(
        required=False, 
        label='Do you need breakfast? ',
        label_suffix = '   --- ',
    )

    comment = forms.CharField(
        widget=forms.Textarea(attrs={
            'placeholder': 'Please leave a comment',
            'class': 'form-control',
            'rows': 2,

        }),
        required = False,
        label_suffix = ''
    )
    class Meta:
        model = BreakfastOrder
        fields = ['comment',]


class LunchOrderForm(forms.ModelForm):
    def get_today():
        return datetime.datetime.today().weekday()

    starter = forms.ModelChoiceField(
        queryset=Starter.objects.filter(tags__tag_name='Lunch', day=get_today()),
        widget=forms.RadioSelect,
        empty_label=None,
        label='Starter',
        required = False,
        label_suffix = ''
    )
    main = forms.ModelChoiceField(
        queryset=Main.objects.filter(tags__tag_name='Lunch', day=get_today()),
        widget=forms.RadioSelect,
        empty_label=None,
        required = False,
        label='Main Course',
        label_suffix = ''
    )
    dessert = forms.ModelChoiceField(
        queryset=Dessert.objects.filter(tags__tag_name='Lunch', day=get_today()),
        widget=forms.RadioSelect,
        empty_label=None,
        required = False,
        label_suffix = ''

    )
    comment = forms.CharField(
        widget=forms.Textarea(attrs={
            'placeholder': 'Please leave a comment',
            'class': 'form-control',
            'rows': 2,

        }),
        required = False,
        label_suffix = ''
    )
    class Meta:
        model = LunchOrder
        fields = ['starter', 'main', 'dessert', 'comment']



class DinnerOrderForm(forms.ModelForm):
    def get_today():
        return datetime.datetime.today().weekday()
        
    starter = forms.ModelChoiceField(
        queryset=Starter.objects.filter(tags__tag_name='Dinner', day=get_today()),
        widget=forms.RadioSelect,
        empty_label=None,
        required = False,
        label_suffix = ''
    )
    main = forms.ModelChoiceField(
        queryset=Main.objects.filter(tags__tag_name='Dinner', day=get_today()),
        widget=forms.RadioSelect,
        empty_label=None,
        required = False,
        label='Main Course',
        label_suffix = ''
    )
    dessert = forms.ModelChoiceField(
        queryset=Dessert.objects.filter(tags__tag_name='Dinner', day=get_today()),
        widget=forms.RadioSelect,
        empty_label=None,
        required = False,
        label_suffix = ''

    )
    comment = forms.CharField(
        widget=forms.Textarea(attrs={
            'placeholder': 'Please leave a comment',
            'class': 'form-control',
            'rows': 2,

        }),
        required = False,
        label_suffix = ''
    )
    class Meta:
        model = DinnerOrder
        fields = ['starter', 'main', 'dessert', 'comment']

django/order_project/order/views.py
from django import forms
from pprint import pprint
from django.views import generic
from django.contrib import messages
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, render, redirect, get_list_or_404


from account.models import Account
from .models import Floor, Room, BreakfastOrder, LunchOrder, DinnerOrder
from .forms import BreakfastOrderForm, LunchOrderForm, DinnerOrderForm



class HomeListView(LoginRequiredMixin, generic.ListView):
    model = Floor
    template_name = 'order/home.html'
    paginate_by = 1

\
    def get_queryset(self):
        self.account = get_object_or_404(Account, email=self.request.user)
        return self.account.floors.all()


class ReportListView(LoginRequiredMixin, generic.ListView):
    model = Floor
    template_name = 'order/report.html'
    paginate_by = 1


    # def get_queryset(self):
    #     self.account = get_object_or_404(Account, email=self.request.user)
    #     return self.account.floors.all()

        

class RoomCreate(SuccessMessageMixin, generic.CreateView):
    model = Room
    fields = ['floor', 'room_num', 'num_guest']
    template_name = 'order/create.html'
    success_url = reverse_lazy('order:home')
    success_message = "%(room_num)s has been created successfully"


    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data
        )


class RoomUpdateView(generic.UpdateView):
    model = Room
    fields = ['room_num', 'num_guest']


class RoomDeleteView(SuccessMessageMixin, generic.DeleteView):
    model = Room
    success_url = reverse_lazy('order:home')
    success_message = "Selected room has been deleted successfully"


    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(RoomDeleteView, self).delete(request, *args, **kwargs)


class BreakfastOrderDeleteView(SuccessMessageMixin, generic.DeleteView):
    model = BreakfastOrder
    success_url = reverse_lazy('order:report')
    success_message = "Selected order has been deleted successfully"
    template_name = 'order/delete.html'


    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(BreakfastOrderDeleteView, self).delete(request, *args, **kwargs)


class LunchOrderDeleteView(SuccessMessageMixin, generic.DeleteView):
    model = LunchOrder
    success_url = reverse_lazy('order:report')
    success_message = "Selected order has been deleted successfully"
    template_name = 'order/delete.html'


    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(LunchOrderDeleteView, self).delete(request, *args, **kwargs)


class DinnerOrderDeleteView(SuccessMessageMixin, generic.DeleteView):
    model = DinnerOrder
    success_url = reverse_lazy('order:report')
    success_message = "Selected order has been deleted successfully"
    template_name = 'order/delete.html'


    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DinnerOrderDeleteView, self).delete(request, *args, **kwargs)


def create_db(request):
    # for fl in range(2, 19):
    #     floor = Floor(floor_num=fl)
    #     floor.save()
    #
    #     for num in range(1, 19):
    #         if fl != 2 and fl != 3:
    #             floor.room_set.create(room_num=fl*100+num)
    #             floor.save()

    return render(request, 'order/create_db.html')


@login_required
def menu(request, pk):
    context = {}
    room = Room.objects.get(id=pk)
    BreakfastOrderFormSet = inlineformset_factory(
        Room, BreakfastOrder, max_num=1, extra=1, can_delete=False,
        form=BreakfastOrderForm,
    )
    LunchOrderFormSet = inlineformset_factory(
        Room, LunchOrder, max_num=1, extra=1, can_delete=False,
        form=LunchOrderForm,
    )
    DinnerOrderFormSet = inlineformset_factory(
        Room, DinnerOrder, max_num=1, can_delete=False,
        form=DinnerOrderForm
    )

    if request.method == 'POST':
        breakfastformset = BreakfastOrderFormSet(request.POST, instance=room, prefix='breakfastform')
        lunchformset = LunchOrderFormSet(request.POST, instance=room, prefix='lunchform')
        dinnerformset = DinnerOrderFormSet(request.POST, instance=room, prefix='dinnerform')

        if lunchformset.is_valid() and dinnerformset.is_valid()  and breakfastformset.is_valid():
            breakfastformset.save()
            lunchformset.save()
            dinnerformset.save()
            return redirect('order:home')
    else:
        breakfastformset = BreakfastOrderFormSet(prefix='breakfastform')
        lunchformset = LunchOrderFormSet(prefix='lunchform')
        dinnerformset = DinnerOrderFormSet(prefix='dinnerform')

    context['breakfastformset'] = breakfastformset
    context['lunchformset'] = lunchformset
    context['dinnerformset'] = dinnerformset
    context['room'] = room


    return render(request, 'order/menu.html', context)

django/order_project/order/templates/order/create.html
{% extends 'base.html' %}


{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {{form}}
  <input type="submit" value="Add New Room">
</form>
{% endblock content %}

django/order_project/order/templates/order/create_db.html
Heloo

django/order_project/order/templates/order/delete.html
<form action="" method="post">
  {% csrf_token %}
  <p><strong>Are you sure you want to delete an order "{{object}}"?</strong></p>
  <a href="{% url 'order:report' %}">Cancel</a>
  <input type="submit" value="Delete">
</form>

django/order_project/order/templates/order/home.html
{% extends 'base.html' %}


{% block content %}

{% include 'snippets/messages.html' %}

<div class="table-wrapper">
  <div class="table-title">
    <div class="row">
      <div class="col-sm-6 d-flex justify-content-center">
        <h2>Manage <b>Rooms</b></h2>
      </div>

      <div class="col-sm-6 d-flex justify-content-center">
        <a href="#addRoomModal" class="btn btn-success" data-toggle="modal">
          <i class="material-icons">&#xE147;</i>
          <span>Add New Room</span>
        </a>
        <a href="#deleteRoomModal" class="btn btn-danger" data-toggle="modal">
          <i class="material-icons">&#xE15C;</i>
          <span>Delete</span>
        </a>
      </div>
    </div>
  </div>


  {% include 'order/snippets/pagination.html'%}


  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr class="text-center">
        <th>Room <i class="fa fa-sort"></i></th>
        <th>B L D <i class="fa fa-sort"></i></th>
        <th>A&K</i></th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for floor in floor_list %}
        {% for room in floor.room_set.all %}
        <tr class="text-center">
          <td><a href="{% url 'order:menu' room.id %}">{{room}}</a></td>
          <td class="text-primary">
            <i class="fas fa-check"></i>
            <i class="fas fa-check"></i>
            <i class="fas fa-check"></i>
          </td>
          <td> 
            {% if room.adult > 1 %}
              <span class="badge badge-danger badge-pill">{{room.adult}}</span>
            {% else %}
              <span class="badge badge-info badge-pill">{{room.adult}}</span>
            {% endif %}
            {% if room.kid %}
              <span class="badge badge-warning badge-pill">{{room.kid}}</span>
            {% endif %}
          </td>
          <td>
            <a href="#viewEmployeeModal" class="view" title="View" data-toggle="modal">
              <i class="material-icons" data-toggle="tooltip" title="View">&#xE417;</i>
            </a>
            <a href="#editEmployeeModal" class="edit" data-toggle="modal">
              <i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i>
            </a>
            <a href="#deleteRoomModal" class="delete" data-toggle="modal">
              <i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i>
            </a>
          </td>
        </tr>
        {% endfor %}
      {% endfor %}
    </tbody>
  </table>

  <!-- Delete Modal HTML -->
  <div id="deleteRoomModal" class="modal fade">
    <div class="modal-dialog modal-confirm">
      <div class="modal-content">
        <div class="modal-header d-flex flex-column align-items-center">
          <div class="icon-box">
            <i class="material-icons">&#xE5CD;</i>
          </div>
          <h4 class="modal-title">Are you sure?</h4>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
          <p>Do you really want to delete this room?</p>
        </div>
        <div class="modal-footer d-flex justify-content-center">
          <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-danger" id="confirmDeleteButtonModal">Delete</button>
        </div>
      </div>
    </div>
  </div>

	<!-- Add Modal HTML -->
  <div id="addRoomModal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
      <form>
        {% csrf_token %}
        <div class="modal-header">
          <h4 class="modal-title">Add Employee</h4>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
          {{form}}
        </div>
        <div class="modal-footer">
          <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
          <input type="submit" class="btn btn-success" value="Add">
        </div>
        </form>
      </div>
    </div>
  </div>

	<!-- Edit Modal HTML -->
	<div id="editEmployeeModal" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<form>
					<div class="modal-header">
						<h4 class="modal-title">Edit Employee</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					<div class="modal-body">
						<div class="form-group">
							<label>Name</label>
							<input type="text" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Email</label>
							<input type="email" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Address</label>
							<textarea class="form-control" required></textarea>
						</div>
						<div class="form-group">
							<label>Phone</label>
							<input type="text" class="form-control" required>
						</div>
					</div>
					<div class="modal-footer">
						<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
						<input type="submit" class="btn btn-info" value="Save">
					</div>
				</form>
			</div>
		</div>
	</div>

</div>

{% include 'order/snippets/pagination.html' %}

{% endblock content %}

django/order_project/order/templates/order/menu.html
{% extends 'base.html' %}


{% block content %}

{% include 'snippets/messages.html' %}

<div class="m-auto pb-5">
  <h3 class="text-center font-weight-bold">Today's Menu</h3>
  <h4 class="text-center text-uppercase font-weight-bold">{{ room }}</h4>
  <p class="text-center alert alert-primary">
  		<i>Please tick one from the choices provided</i>
  </p>
  <form action="" method="post">
    {% csrf_token %}
    <h3 id="lunch" class="text-center text-primary">Breakfast</h3>
      {{breakfastformset}}
      

    <h3 id="lunch" class="text-center text-primary">Lunch Menu</h3>
      {{lunchformset}}

    <h3 id="dinner" class="text-center text-primary">Dinner Menu</h3>
    {{dinnerformset}}

    <a href="{% url 'order:home' %}" class="btn btn-primary btn-lg btn-block mt-2">
      Cancel
    </a>
    <button type="submit" class="btn btn-primary btn-lg btn-block mt-2">
      Send
    </button>
    <button type="submit" class="btn btn-primary btn-lg btn-block mt-2">
      Send and Next Room
    </button>
  </form>
</div>



{% endblock content %}

django/order_project/order/templates/order/report.html
{% extends 'base.html' %}

{% block content %}
<div class="table-wrapper">
  <div class="table-title">
    <div class="row">
      <div class="col-sm-6 d-flex justify-content-center">
        <h2>Order <b>Details</b></h2>
      </div>
      <div class="col-sm-6 d-flex justify-content-center">            
        <a href="#" class="btn btn-primary"><i class="material-icons">&#xE863;</i> <span>Refresh List</span></a>
        <a href="#" class="btn btn-info"><i class="material-icons">&#xE24D;</i> <span>Export to Excel</span></a>
      </div>
    </div>
  </div>


  <div class="table-filter">
    <div class="row">
      <div class="col-sm-3">
        <div class="show-entries">
          <span>Show</span>
          <select class="form-control">
            <option>5</option>
            <option>10</option>
            <option>15</option>
            <option>20</option>
          </select>
          <span>entries</span>
        </div>
      </div>
    <div class="col-sm-9">
      <div class="filter-group">
        <label>Room</label>
        <input type="text" class="form-control">
        <button type="button" class="btn btn-primary">
          <i class="fa fa-search"></i>
        </button>
      </div>
      <div class="filter-group">
        <label>Meal</label>
        <select class="form-control">
          <option>All</option>
          <option>Breakfast</option>
          <option>Lunch</option>
          <option>Dinner</option>
        </select>
      </div>
      <div class="filter-group">
        <label>Status</label>
        <select class="form-control">
          <option>Any</option>
          <option>Delivered</option>
          <option>Pending</option>
          <option>Cancelled</option>
        </select>
      </div>
    </div>
    </div>
  </div>


  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Room</th>
        <th>Starter</th>
        <th>Main Course</th>
        <th>Dessert</th>           
        <th>Status</th>           
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td><a href="#"><img src="/examples/images/avatar/1.jpg" class="avatar" alt="Avatar"> Michael Holz</a></td>
        <td>London</td>
        <td>Jun 15, 2017</td>                        
        <td><span class="status text-success">&bull;</span> Delivered</td>
        <td><a href="#" class="view" title="View Details" data-toggle="tooltip"><i class="material-icons">&#xE5C8;</i></a></td>
      </tr>
      <tr>
        <td>3</td>
        <td><a href="#"><img src="/examples/images/avatar/3.jpg" class="avatar" alt="Avatar"> Antonio Moreno</a></td>
        <td>Berlin</td>
        <td>Jul 04, 2017</td>
        <td><span class="status text-danger">&bull;</span> Cancelled</td>
        <td><a href="#" class="view" title="View Details" data-toggle="tooltip"><i class="material-icons">&#xE5C8;</i></a></td>                        
      </tr>
      <tr>
        <td>4</td>
        <td><a href="#"><img src="/examples/images/avatar/4.jpg" class="avatar" alt="Avatar"> Mary Saveley</a></td>
        <td>New York</td>
        <td>Jul 16, 2017</td>           
        <td><span class="status text-warning">&bull;</span> Pending</td>
        <td><a href="#" class="view" title="View Details" data-toggle="tooltip"><i class="material-icons">&#xE5C8;</i></a></td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}