django/order_project/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('passwd_change/', views.PasswdChangeView.as_view(), name='password_change'),
    path('passwd_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('passwd_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

]

django/order_project/order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('', views.HomeListView.as_view(), name='home'),
    path('report/', views.ReportListView.as_view(), name='report'),
    path('menu/<int:pk>/', views.menu, name='menu'),
    path('del_b/<int:pk>/', views.BreakfastOrderDeleteView.as_view(), name='delete_b'),
    path('del_l/<int:pk>/', views.LunchOrderDeleteView.as_view(), name='delete_l'),
    path('del_d/<int:pk>/', views.DinnerOrderDeleteView.as_view(), name='delete_d'),


    # path('create/', views.RoomCreate.as_view(), name='create'),
    # path('delete/<int:pk>/', views.RoomDeleteView.as_view(), name='delete'),
    # path('create_db/', views.create_db, name='create_db'),
]

django/order_project/order_project/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('order/', include('order.urls')),
]

django/order_project/templates/snippets/messages.html
{% if messages %}
  {% for message in messages %}
  <p class="alert alert-{{message.tags}}">{{message}}</p>
  {% endfor %}
{% endif %}

django/order_project/templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'order:home' %}">Millennium Plaza</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'order:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Tomorrow</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'order:report' %}">My Orders</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:password_change' %}">Password Change</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:logout'%}">Sign Out</a>
      </li>
    </ul>
  </div>
</nav>